---
- name: Check Apache status
  hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    - name: Check Apache service status
      command: systemctl status apache2
      register: response

    - debug:
        var: response
